### PR TITLE
perf: add support to laravel 9

### PR DESCRIPTION
**Pull request by lsnepomuceno**

### CODE REVIEW

**Comment by lsnepomuceno** [comment]
@Naoray 
Is this package still maintained?

**Comment by Naoray** [comment]
@lsnepomuceno I've not abonded this pkg yet and will continue to maintain it whenever I find the time to do it.

Regarding your PR:
I am not 100% confident that bumping the version will do the trick for upgrading to laravel v9. Will check within the next days.

**Comment by 1e4** [comment]
Did you manage to follow up? Is this ok to upgrade now?

**Comment by Naoray** [comment]
@1e4 sorry, I've not have the time nor the will to look into this. Since I didn't find the time during the last month and I don't use this package personally anymore, I will abandon it. Feel free to fork it and maintain your own version of it.

**Pull request closed without merging**
